name: pro-odoroki

channels:
  - conda-forge

dependencies:
  - python==3.11
  - pytest
  - pytest-cov
  - pre-commit
  - pandas
  - scikit-learn
  - pip
  - pip:
    - -r aws_chalice/requirements.txt
