name: Source Code Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Git Clone Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11
          environment-file: environment.yml
          activate-environment: ds
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ExecutionRoleForGitHubAction
          role-session-name: github-action-session
          aws-region: us-east-1
      - name: CI/CD
        shell: bash -l {0}
        run: pre-commit run --all-files
